### ISSUE TITLE
Create vhost for varnish dev page

### ISSUE THREAD

**Issue by Jesmaster** [avatarnewyork/dockerenv_apache#20]
Most of our sites have some kind of code to check if it's running locally looking for "avatarnewyork.com" in the http host. This functionality breaks when using the current varnish dev url "10.2.0.10:port". Can you make another vhost for the varnish version like mysite-varnish.dev.avatarnewyork.com?

**Comment by mrpatrick** [comment]
Moved to varnish project: https://github.com/avatarnewyork/docker-varnish/issues/3
