### ISSUE TITLE
set xdebug.max_nesting_level to 250

### ISSUE THREAD

**Issue by mrpatrick** [avatarnewyork/dockerenv_apache#31]
@dragansefo 
> can you change the max nesting level for xdebug? i've been meaning to tell you about the xdebug max nesting and symfony. This is from check.php.

```
WARNING  xdebug.max_nesting_level should be above 100 in php.ini
         Set "xdebug.max_nesting_level" to e.g. "250" in php.ini* to stop Xdebug's infinite recursion protection erroneously throwing a fatal error in your project.
```

While this fix is being addressed in the image, you can set this limit in .htaccess:

```ini
php_value  max_input_nesting_level 1000
```

**Comment by zoneradx** [comment]
Can any one tell me where to add xdebug.max_nesting_level=200.I didnot find it in pnp.ini?

**Comment by mrpatrick** [comment]
Hi @zoneradx - we set it to 300 here: 

https://github.com/avatarnewyork/dockerenv_apache/blob/master/root/etc/php.ini

for master/php53/php56 branches.  If you want to override it to 200, you can set it in .htaccess (as described in the original ticket) or you can fork the project and build it with your settings.  Thanks!

Pat
